### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by kashev** [daranguiz/barbell-io#2]
Create a `requirements.txt` file at the top level of the repository which contains the python dependencies for the project.

@daranguiz run `pip freeze > requirements.txt` inside of your virtualenv, and commit the file.

**Comment by daranguiz** [comment]
I've now screwed this up twice now, but, CLOSED.

**Comment by kashev** [comment]
I realized that a lot of these are probably derived dependencies. It's not super important, but some time, down the road, we should sit down, decide what's strictly necessary, and then only list those.

**Comment by daranguiz** [comment]
Agreed. I think some of those were leftovers from the microblog tutorial as well.
