### ISSUE TITLE
Create a `manage.py`, similar to Django Project Structure

### ISSUE THREAD

**Issue by kashev** [daranguiz/barbell-io#3]
I think that one thing that Django does right, over flask, is the `manage.py` paradigm, where top level project actions, like running the project in debug mode or not, cleaning built files, etc, are contained in one script. Here's an example I wrote once upon a time which uses [flask script](https://flask-script.readthedocs.io/en/latest/) which I think demonstrates the power of this approach:

https://github.com/kashev/kashev.rocks/blob/master/manage.py

I think this is cleaner than having `run.py` and `runp.py` at the top level. This particular example shows cleaning of built assets and a livereloading server, which I find particularly useful.

Thoughts?

**Comment by kashev** [comment]
Also, all of the database creation/migration scripts can be consolidated into here, so they don't clutter the top level.

**Comment by daranguiz** [comment]
I have absolutely zero experience in best practices for directory layout. This is all you.

**Comment by daranguiz** [comment]
closed with #24
