### ISSUE TITLE
Add a livereloading development server

### ISSUE THREAD

**Issue by kashev** [daranguiz/barbell-io#4]
Add a livereloading server to the project so we don't have to press `ctrl+r` (or `ctrl+shift+r`) ever again. I have used [python-livereload](https://github.com/lepture/python-livereload) in conjunction with the [Chrome Extension](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?utm_source=chrome-app-launcher-info-dialog)  and enjoyed the results.

**Comment by daranguiz** [comment]
seems nice, I'm not opposed

**Comment by daranguiz** [comment]
Would be useful, but it's not MVP

**Comment by kashev** [comment]
you are right

**Comment by kashev** [comment]
ugh still don't have the hang of closing the issue with the actual merge
